Non-functional: exit early if PR job

diff --git a/hooks/post-command b/hooks/post-command
--- a/hooks/post-command
+++ b/hooks/post-command
@@ -15,27 +15,25 @@ if [[ -z $PIPELINE ]]; then
     echo "No pipeline ID found, skipping factory reporter"
     exit 0
 fi
-
-if [[ $BUILDKITE_PULL_REQUEST == "false" ]]; then
-
-  START_SECONDS=$(buildkite-agent meta-data get start-seconds)
-  if [[ -z $START_SECONDS ]]; then
-    echo "Error: start-seconds not set as meta-data" >&2
-    exit 1
-  fi
-  echo "Build started at $START_SECONDS"
-
-  FACTORY_COMMAND=$(buildkite-agent meta-data get factory-command)
-  if [[ -z $FACTORY_COMMAND ]]; then
-    echo "Error: factory-command not set as meta-data" >&2
-    exit 1
-  fi
-  echo "Using factory command: $FACTORY_COMMAND"
-
-
-  JOB_JSON=$($FACTORY_COMMAND update-buildkite-job-run $START_SECONDS $PIPELINE "success")
-  echo "Output from updating job run : $JOB_JSON"
-else
-  echo "This is a pull request, skipping factory reporter"
-  exit 0
+if [[ $BUILDKITE_PULL_REQUEST != "false" ]]; then
+    echo "This is a pull request, skipping factory reporter"
+    exit 0
 fi
+
+START_SECONDS=$(buildkite-agent meta-data get start-seconds)
+if [[ -z $START_SECONDS ]]; then
+  echo "Error: start-seconds not set as meta-data" >&2
+  exit 1
+fi
+echo "Build started at $START_SECONDS"
+
+FACTORY_COMMAND=$(buildkite-agent meta-data get factory-command)
+if [[ -z $FACTORY_COMMAND ]]; then
+  echo "Error: factory-command not set as meta-data" >&2
+  exit 1
+fi
+echo "Using factory command: $FACTORY_COMMAND"
+
+
+JOB_JSON=$($FACTORY_COMMAND update-buildkite-job-run $START_SECONDS $PIPELINE "success")
+echo "Output from updating job run : $JOB_JSON"
